version: "2"
services:
  # このイメージのバージョンアップ = wordpress, PHPのバージョンアップ
  wordpress:
    container_name: ${WORDPRESS_CONTAINER}
    build: ./settings/wp
    ports:
      - "${EXPOSE_WP_PORT}:9000"
    links:
      - db
    environment:
      WORDPRESS_DB_HOST: "db:3306"
    env_file: .env
    volumes:
      - ./wordpress/themes/fl:/var/www/html/wp-content/themes/fl
      - ./wordpress/plugins:/var/www/html/wp-content/plugins
      - ./wordpress/uploads:/var/www/html/wp-content/uploads
      - ./tools/wordmove:/var/www/tools/wordmove
      - ./tools/shell-scripts/lib:/var/www/tools/shell-scripts
      - ./.env:/var/www/.env
      - ~/.ssh:/root/.ssh
    networks:
      main:
        aliases:
          - wp
  nginx:
    container_name: ${NGINX_CONTAINER}
    image: nginx:alpine
    env_file: .env
    ports:
      - "${EXPOSE_WEB_PORT}:80"
    volumes:
      - ./settings/nginx:/etc/nginx/conf.d
      - ./logs/nginx:/var/log/nginx
    volumes_from:
      - wordpress
    links:
      - wordpress
    networks:
      main:
        aliases:
          - web
  db:
    container_name: ${MYSQL_CONTAINER}
    image: mariadb:latest
    env_file: .env
    volumes:
      - ./settings/db:/etc/mysql/data
    networks:
      main:
        aliases:
          - db
networks:
  main:
